services:
  MenAtWork\ClipboardBundle\Helper\ContaoBridge:

  MenAtWork\ClipboardBundle\Helper\Database:
    arguments:
      - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'

  MenAtWork\ClipboardBundle\Helper\Base:
    arguments:
      - '@MenAtWork\ClipboardBundle\Helper\Database'
      - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'

    MenAtWork\ClipboardBundle\Xml\Writer:
      arguments:
        - '@MenAtWork\ClipboardBundle\Helper\Base'
        - '@MenAtWork\ClipboardBundle\Helper\Database'
        - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'

    MenAtWork\ClipboardBundle\Xml\Reader:
      arguments:
        - '@MenAtWork\ClipboardBundle\Helper\Base'
        - '@MenAtWork\ClipboardBundle\Helper\Database'
        - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'

    MenAtWork\ClipboardBundle\Xml\Base:
      arguments:
        - '@MenAtWork\ClipboardBundle\Xml\Reader'
        - '@MenAtWork\ClipboardBundle\Xml\Writer'
        - '@MenAtWork\ClipboardBundle\Helper\Base'
        - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'

    MenAtWork\ClipboardBundle\Factory\XmlElement:
      arguments:
        - '@MenAtWork\ClipboardBundle\Helper\Base'
        - '@MenAtWork\ClipboardBundle\Xml\Writer'
        - '@MenAtWork\ClipboardBundle\Xml\Reader'
        - '@MenAtWork\ClipboardBundle\Helper\ContaoBridge'










